### ISSUE TITLE
Bookmark function fails for paused music

### ISSUE THREAD

**Issue by aflynn73** [142West/Shots-Alarm#1]
When bookmark function is run on paused music, it is unable to get the progress of the currently playing track (for obvious reasons).

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/gpiozero/pins/rpigpio.py", line 244, in _call_when_changed
    super(RPiGPIOPin, self)._call_when_changed()
  File "/usr/local/lib/python3.7/dist-packages/gpiozero/pins/local.py", line 143, in _call_when_changed
    self.state if state is None else state)
  File "/usr/local/lib/python3.7/dist-packages/gpiozero/pins/pi.py", line 293, in _call_when_changed
    method(ticks, state)
  File "/usr/local/lib/python3.7/dist-packages/gpiozero/input_devices.py", line 197, in _pin_changed
    self._fire_events(ticks, bool(self._state_to_value(state)))
  File "/usr/local/lib/python3.7/dist-packages/gpiozero/mixins.py", line 368, in _fire_events
    self._fire_activated()
  File "/usr/local/lib/python3.7/dist-packages/gpiozero/mixins.py", line 397, in _fire_activated
    super(HoldMixin, self)._fire_activated()
  File "/usr/local/lib/python3.7/dist-packages/gpiozero/mixins.py", line 344, in _fire_activated
    self.when_activated()
  File "/home/mop/Python/ShotsAlarm/src/shotsAlarm2.0.py", line 278, in alarmActivate
    # save our current spot
  File "/home/mop/Python/ShotsAlarm/src/util/ShotsAlarmSpotipy.py", line 100, in saveSpot
    theTrack.append(self.getCurrentProgress(trackData))
  File "/home/mop/Python/ShotsAlarm/src/util/ShotsAlarmSpotipy.py", line 69, in getCurrentProgress
    cProgress = trackData['progress_ms']
TypeError: 'NoneType' object is not subscriptable

**Comment by aflynn73** [comment]
Addressed by [590cb1e](https://github.com/142West/Shots-Alarm/commit/590cb1eb223a08301518461b6a5ed252fadcf723). Added if statement in saveSpot() so as to not attempt to process None in subsequent function calls.
